### PR TITLE
ASAN

### PR DESCRIPTION
**Pull request by g0djan**

### CODE REVIEW

**Comment by x4m** [comment]
Thanks, pushed

**Comment by evarganov** [comment]
After this commit we have a problem with build
**odyssey_1  | [ 30%] Building C object sources/CMakeFiles/odyssey.dir/pam.c.o
odyssey_1  | [ 31%] Linking C executable odyssey
odyssey_1  | /usr/bin/ld: ../third_party/machinarium/sources/libmachinarium.a(signal_mgr.c.o): undefined reference to symbol 'pthread_sigmask@@GLIBC_2.2.5'
odyssey_1  | //lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
odyssey_1  | collect2: error: ld returned 1 exit status
odyssey_1  | sources/CMakeFiles/odyssey.dir/build.make:752: recipe for target 'sources/odyssey' failed
odyssey_1  | make[2]: *** [sources/odyssey] Error 1
odyssey_1  | CMakeFiles/Makefile2:192: recipe for target 'sources/CMakeFiles/odyssey.dir/all' failed
odyssey_1  | make[1]: *** [sources/CMakeFiles/odyssey.dir/all] Error 2
odyssey_1  | make: *** [all] Error 2
odyssey_1  | Makefile:83: recipe for target 'all' failed
docker_odyssey_1 exited with code 2
**

**Comment by x4m** [comment]
@evarganov this commit only change debug build. Probably, it is related to cmake files and pthread linkage, I will look into this in few days

**Comment by x4m** [comment]
@evarganov after toying with greenplum build I've modified something in my system and currently get same error.
I've temporary fixed it this way
x4mmm@x4mmm-2osx odyssey % git diff
```
diff --git a/sources/CMakeLists.txt b/sources/CMakeLists.txt
index 4c09182..aa18e62 100644
--- a/sources/CMakeLists.txt
+++ b/sources/CMakeLists.txt
@@ -47,4 +47,4 @@ if(THREADS_HAVE_PTHREAD_ARG)
     set_property(TARGET ${od_binary} PROPERTY INTERFACE_COMPILE_OPTIONS "-pthread")
 endif()
 
-target_link_libraries(${od_binary} ${od_libraries} ${CMAKE_THREAD_LIBS_INIT})
+target_link_libraries(${od_binary} ${od_libraries} ${CMAKE_THREAD_LIBS_INIT} pthread)
```
ButI think there must be more generic solution

**Comment by x4m** [comment]
@evarganov can you plz check that #126 helps?

**Comment by evarganov** [comment]
> @evarganov can you plz check that #126 helps?

Thx! Everything is ok now

**Pull request merged**
