### PR TITLE
fix memory leak when using scram

### PR DESCRIPTION
**Pull request by kt315**
Fixed some errors leading to memory leaks when using scram.

### CODE REVIEW

**Comment by sukhinov** [comment]
Thanks a lot. It helped me a lot.

**Comment by Alexander-Vays** [comment]
Oh, that's what I was looking for. Thanks.

**Review by Alexander-Vays — APPROVED** [review]

**Review by Alexander-Vays — APPROVED** [review]

**Comment by ap200984** [comment]
Awesome! Thank you!

**Review by x4m — APPROVED** [review]
Thanks! Pushed.
(sorry, I missed notification while on pgconf)

**Pull request merged**
