### PR TITLE
Added spec file for CentOS 7 & systemd units

### PR DESCRIPTION
**Pull request by sklochkov**
Added a spec file for CentOS 7 build & normal and instanced units for systemd.

### CODE REVIEW

**Comment by pmwkaa** [comment]
Thank you! Can we move those files to scripts/centos/ directory or they must be put in root directory to work?

**Comment by sklochkov** [comment]
Since systemd is used not only on CentOS, it would make sense to put the unit files to a systemd/ directory. I'll need to update the spec file for that to work.

Also, what's the current version of odyssey? I found 3.0 in the debian/ directory.

**Comment by sklochkov** [comment]
The spec file can be put anywhere, it will work from anywhere if the correct tarball is present in rpmbuild/SOURCES

**Comment by pmwkaa** [comment]
scripts/systemd/ sounds good to me, lets use it. 

I believe this should be 1.0 beta. I think to stick to semantic versioning (https://semver.org/) should be a good idea

**Comment by sklochkov** [comment]
Ok, then it would make sense to change the Version line in the spec file.

**Comment by sklochkov** [comment]
Done.

**Pull request merged**
