### PR TITLE
CI: make coverity scan run on schedule

### PR DESCRIPTION
**Pull request by chipitsine**

### CODE REVIEW

**Comment by chipitsine** [comment]
ping ?

**Review by x4m — APPROVED** [review]

**Comment by x4m** [comment]
Sorry, I’ve missed this PR. Looks good to me. Let’s check it does not break CI. Plz rebase or push something.

**Comment by chipitsine** [comment]
it only changes `.github/workflows/coverity.yml`, even if pull request CI fails, it should be whatever reason, but not my change

**Comment by x4m** [comment]
Thanks! Pushed

**Pull request merged**
