### PR TITLE
Add support for server host logging by %H

### PR DESCRIPTION
**Pull request by ilya-maltsev**

### CODE REVIEW

**Comment by reshke** [comment]
Please run `make apply_fmt`

**Review by ilya-maltsev — COMMENTED** [review]
requested changes have been made

**Comment by reshke** [comment]
hmm seems like tests are failed again, will run clang-format myself ;)

**Comment by ilya-maltsev** [comment]
better luck next time)

**Comment by reshke** [comment]
i will investigate failed tests, it seems to be flaky

**Comment by ilya-maltsev** [comment]
i will reopen it in another request with optimized code

**Pull request closed without merging**
